import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./sidebar";
import { Breadcrumb, Layout, Menu, theme } from "antd";
import { Children } from "react";
const { Header, Content, Footer, Sider } = Layout;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Layout
            style={{
              minHeight: "100vh",
            }}
          >
            <Sidebar />
            <div className="max-w-full max-h-full">{children}</div>
          </Layout>
      </body>
    </html>
  );
}
